from app.models import db, Review, environment, SCHEMA
from sqlalchemy.sql import text

seed_data = [
    ## user 1
    {
        "description": "Embark on a stunning trail and immerse yourself in nature's wonders. Breathtaking landscapes, serene lakes, and majestic mountains await.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 1,
    },
    {
        "description": "Experience the awe-inspiring beauty of a scenic hiking path with panoramic vistas and enchanting landscapes. Unforgettable moments await.",
        "rating": 3,
        "trail_id": 2,
        "user_id": 1,
    },
    {
        "description": "Discover a hidden gem, an amazing trail winding through lush greenery. Unveil nature's secrets and find tranquility in the wilderness.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 1,
    },
    {
        "description": "Embark on a captivating trail that showcases stunning landscapes. From rugged mountains to serene meadows, nature's beauty surrounds you.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 1,
    },
    {
        "description": "Indulge your senses in a scenic trail with panoramic vistas and a serene ambiance. Let nature's grandeur leave you in awe.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 1,
    },
    {
        "description": "Get lost in the magnificence of a mesmerizing trail with breathtaking mountain views at every turn. Adventure awaits.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 1,
    },
    {
        "description": "Escape to a tranquil forest oasis and explore a spectacular trail leading to serenity and inner peace. Find solace in nature's embrace.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 1,
    },
    {
        "description": "Unwind and reconnect with nature on a tranquil trail, where solitude and tranquility abound in every step. Find serenity within.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 1,
    },
    {
        "description": "Immerse yourself in the beauty of a picturesque trail with stunning lake views. Let nature's splendor be your backdrop.",
        "rating": 5,
        "trail_id": 9,
        "user_id": 1,
    },
    {
        "description": "Embark on an unforgettable journey through an exquisite trail amidst breathtaking natural beauty. Create lasting memories in nature's embrace.",
        "rating": 3,
        "trail_id": 10,
        "user_id": 1,
    },
    ## user 2
    {
        "description": "Experience the tranquility of a hidden gem, surrounded by lush forests and gentle streams. Nature's beauty awaits at every turn.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 2,
    },
    {
        "description": "Embark on an adventurous trail that winds through towering mountains and offers breathtaking panoramic views. Nature's wonders await.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 2,
    },
    {
        "description": "Discover a peaceful trail nestled in a serene valley, where colorful wildflowers and singing birds accompany your journey.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 2,
    },
    {
        "description": "Immerse yourself in the diversity of a captivating trail that transitions from lush forests to dramatic cliffs and tranquil meadows.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 2,
    },
    {
        "description": "Indulge in a scenic trail adorned with breathtaking vistas, where the beauty of nature unfolds before your eyes.",
        "rating": 3,
        "trail_id": 5,
        "user_id": 2,
    },
    {
        "description": "Get enchanted by a mesmerizing trail offering sweeping views of majestic mountains and valleys drenched in golden sunlight.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 2,
    },
    {
        "description": "Escape to a tranquil forest sanctuary, where a picturesque trail leads you to discover hidden waterfalls and peaceful solitude.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 2,
    },
    {
        "description": "Find inner peace on a rejuvenating trail that meanders through serene meadows, surrounded by the soothing sounds of nature.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 2,
    },
    {
        "description": "Immerse yourself in the beauty of a scenic trail adorned with shimmering lakes, reflecting the surrounding mountains in all their glory.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 2,
    },
    {
        "description": "Embark on an unforgettable adventure through an exquisite trail, where nature's beauty unfolds in every step you take.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 2,
    },
    ## user 3
    {
        "description": "Immerse yourself in a serene oasis, where a tranquil trail winds through lush green forests and leads to hidden waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 3,
    },
    {
        "description": "Embark on an exhilarating journey through a rugged trail that offers breathtaking views of snow-capped peaks and untouched wilderness.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 3,
    },
    {
        "description": "Discover a hidden paradise, a trail that takes you through vibrant meadows, where colorful wildflowers paint the landscape.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 3,
    },
    {
        "description": "Immerse yourself in nature's grandeur as you explore a diverse trail, traversing dense forests, rocky terrains, and tranquil rivers.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 3,
    },
    {
        "description": "Witness the awe-inspiring beauty of a scenic trail adorned with majestic vistas, where the harmony of nature unfolds before your eyes.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 3,
    },
    {
        "description": "Embark on a captivating trail that leads you to mesmerizing mountain peaks, where panoramic views leave you in awe of the world's wonders.",
        "rating": 5,
        "trail_id": 6,
        "user_id": 3,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail unveils hidden ponds, babbling brooks, and a symphony of birdsong.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 3,
    },
    {
        "description": "Immerse yourself in the tranquility of a serene trail, where each step brings you closer to inner peace and a deeper connection with nature.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 3,
    },
    {
        "description": "Experience the magic of a scenic trail that winds along crystal-clear lakes, reflecting the beauty of the surrounding landscapes.",
        "rating": 5,
        "trail_id": 9,
        "user_id": 3,
    },
    {
        "description": "Embark on an unforgettable adventure through an exquisite trail, where nature's marvels unfold in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 3,
    },
    ## user 4
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a peaceful trail winds through lush forests and leads to hidden gems.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 4,
    },
    {
        "description": "Embark on an exhilarating journey through a rugged trail that unveils breathtaking vistas of towering peaks and untouched wilderness.",
        "rating": 4,
        "trail_id": 2,
        "user_id": 4,
    },
    {
        "description": "Discover a hidden paradise, a trail that meanders through colorful meadows, where vibrant wildflowers create a mesmerizing tapestry.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 4,
    },
    {
        "description": "Immerse yourself in nature's grandeur as you explore a diverse trail, traversing dense forests, rocky terrains, and peaceful rivers.",
        "rating": 5,
        "trail_id": 4,
        "user_id": 4,
    },
    {
        "description": "Witness the awe-inspiring beauty of a scenic trail adorned with majestic vistas, where the wonders of nature unfold before your eyes.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 4,
    },
    {
        "description": "Embark on a captivating trail that leads you to breathtaking mountain peaks, where panoramic views leave you in awe of nature's majesty.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 4,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 4,
    },
    {
        "description": "Immerse yourself in the serenity of a peaceful trail, where every step brings you closer to inner peace and a deeper connection with nature.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 4,
    },
    {
        "description": "Experience the magic of a scenic trail that winds along crystal-clear lakes, reflecting the beauty of the surrounding landscapes.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 4,
    },
    {
        "description": "Embark on an unforgettable adventure through an exquisite trail, where nature's marvels unfold in a symphony of sights, scents, and sounds.",
        "rating": 3,
        "trail_id": 10,
        "user_id": 4,
    },
    {
        "description": "Explore a hidden paradise as you traverse a serene trail surrounded by lush greenery and discover hidden waterfalls along the way.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 5,
    },
    {
        "description": "Embark on an invigorating journey through a challenging trail that rewards you with awe-inspiring vistas of untouched natural landscapes.",
        "rating": 4,
        "trail_id": 2,
        "user_id": 5,
    },
    {
        "description": "Discover a picturesque trail that meanders through vibrant meadows adorned with a myriad of wildflowers, creating a captivating tapestry.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 5,
    },
    {
        "description": "Immerse yourself in the majesty of nature as you navigate a diverse trail, encountering dense forests, rugged terrains, and tranquil streams.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 5,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's wonders unfold in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 5,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 5,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, gentle streams, and a symphony of bird songs.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 5,
    },
    {
        "description": "Find inner peace and serenity on a peaceful trail, where each step connects you with nature and rejuvenates your body and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 5,
    },
    {
        "description": "Experience the magic of a scenic trail that winds alongside crystal-clear lakes, offering breathtaking views and tranquility in abundance.",
        "rating": 5,
        "trail_id": 9,
        "user_id": 5,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where the beauty of nature unfolds in a symphony of sights and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 5,
    },
    {
        "description": "Embark on a captivating journey as you follow a serene trail that winds through lush forests and reveals hidden cascading waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 6,
    },
    {
        "description": "Challenge yourself on an exhilarating trail that takes you through rugged terrains, rewarding you with breathtaking views of untouched wilderness.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 6,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 4,
        "trail_id": 3,
        "user_id": 6,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil rivers.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 6,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail boasting majestic vistas, where nature's splendor unfolds in panoramic grandeur.",
        "rating": 3,
        "trail_id": 5,
        "user_id": 6,
    },
    {
        "description": "Embark on an unforgettable adventure along a captivating trail, leading you to breathtaking mountain peaks and awe-inspiring landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 6,
    },
    {
        "description": "Escape to a tranquil forest sanctuary, where a picturesque trail unveils hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 6,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 6,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 6,
    },
    {
        "description": "Embark on an extraordinary journey through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 5,
        "trail_id": 10,
        "user_id": 6,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail meanders through lush forests and reveals enchanting waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 7,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that rewards you with breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 4,
        "trail_id": 2,
        "user_id": 7,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a tapestry of colors and nature's splendor.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 7,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and serene rivers.",
        "rating": 5,
        "trail_id": 4,
        "user_id": 7,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail boasting majestic vistas, where nature's grandeur unfolds in panoramic splendor.",
        "rating": 5,
        "trail_id": 5,
        "user_id": 7,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail, leading you to breathtaking mountain peaks and awe-inspiring natural landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 7,
    },
    {
        "description": "Escape to a tranquil forest sanctuary, where a picturesque trail unveils hidden ponds, babbling brooks, and a symphony of wildlife melodies.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 7,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 7,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 7,
    },
    {
        "description": "Embark on an extraordinary journey through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 5,
        "trail_id": 10,
        "user_id": 7,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 8,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 8,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 8,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 5,
        "trail_id": 4,
        "user_id": 8,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 8,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 8,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 8,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 8,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 5,
        "trail_id": 9,
        "user_id": 8,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 8,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail meanders through lush forests and reveals captivating waterfalls.",
        "rating": 5,
        "trail_id": 1,
        "user_id": 9,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 9,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 9,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and serene rivers.",
        "rating": 5,
        "trail_id": 4,
        "user_id": 9,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 9,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 5,
        "trail_id": 6,
        "user_id": 9,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 9,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 9,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 9,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 5,
        "trail_id": 10,
        "user_id": 9,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 10,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 4,
        "trail_id": 2,
        "user_id": 10,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 10,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 3,
        "trail_id": 4,
        "user_id": 10,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 10,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 10,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 10,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 10,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 10,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 10,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 11,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 11,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 11,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 11,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 11,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 11,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 11,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 11,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 5,
        "trail_id": 9,
        "user_id": 11,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 5,
        "trail_id": 10,
        "user_id": 11,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 12,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 12,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 12,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 2,
        "trail_id": 4,
        "user_id": 12,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 5,
        "trail_id": 5,
        "user_id": 12,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 12,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 12,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 4,
        "trail_id": 8,
        "user_id": 12,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 12,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 12,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 13,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 13,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 13,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 13,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 5,
        "trail_id": 5,
        "user_id": 13,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 13,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 5,
        "trail_id": 7,
        "user_id": 13,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 13,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 2,
        "trail_id": 9,
        "user_id": 13,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 5,
        "trail_id": 10,
        "user_id": 13,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 14,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 5,
        "trail_id": 2,
        "user_id": 14,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 14,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 4,
        "trail_id": 4,
        "user_id": 14,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 4,
        "trail_id": 5,
        "user_id": 14,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 14,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 14,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 14,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 14,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 14,
    },
    {
        "description": "Immerse yourself in the tranquility of a hidden oasis, where a serene trail winds through lush forests and reveals mesmerizing waterfalls.",
        "rating": 4,
        "trail_id": 1,
        "user_id": 15,
    },
    {
        "description": "Embark on an exhilarating adventure along a rugged trail that unveils breathtaking vistas of untouched wilderness and rugged landscapes.",
        "rating": 3,
        "trail_id": 2,
        "user_id": 15,
    },
    {
        "description": "Discover a picturesque trail adorned with vibrant meadows, where blooming wildflowers create a colorful tapestry of natural beauty.",
        "rating": 5,
        "trail_id": 3,
        "user_id": 15,
    },
    {
        "description": "Immerse yourself in the wonders of nature as you navigate a diverse trail, encountering dense forests, rocky cliffs, and tranquil streams.",
        "rating": 5,
        "trail_id": 4,
        "user_id": 15,
    },
    {
        "description": "Witness the enchanting beauty of a scenic trail adorned with majestic vistas, where nature's splendor unfolds in breathtaking panoramas.",
        "rating": 5,
        "trail_id": 5,
        "user_id": 15,
    },
    {
        "description": "Embark on an unforgettable journey along a captivating trail that leads you to awe-inspiring mountain peaks and breathtaking landscapes.",
        "rating": 4,
        "trail_id": 6,
        "user_id": 15,
    },
    {
        "description": "Escape to a tranquil forest retreat, where a picturesque trail reveals hidden ponds, babbling brooks, and a symphony of wildlife.",
        "rating": 4,
        "trail_id": 7,
        "user_id": 15,
    },
    {
        "description": "Find solace and serenity on a peaceful trail, where each step connects you with nature, rejuvenating your mind, body, and soul.",
        "rating": 5,
        "trail_id": 8,
        "user_id": 15,
    },
    {
        "description": "Experience the magic of a scenic trail winding alongside crystal-clear lakes, offering breathtaking views and a sense of tranquility.",
        "rating": 4,
        "trail_id": 9,
        "user_id": 15,
    },
    {
        "description": "Embark on an extraordinary adventure through an exquisite trail, where nature's beauty unfolds in a symphony of sights, scents, and sounds.",
        "rating": 4,
        "trail_id": 10,
        "user_id": 15,
    },
]


# @with_appcontext
def seed_reviews(app):
    with app.app_context():
        for data in seed_data:
            review = Review(**data)
            db.session.add(review)

        db.session.commit()


# @with_appcontext
def undo_reviews(app):
    with app.app_context():
        if environment == "production":
            db.session.execute(
                f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;"
            )
        else:
            db.session.execute(text("DELETE FROM reviews"))

        db.session.commit()
