from app.models import db, Trail, environment, SCHEMA
from sqlalchemy.sql import text

seed_data = [
    {
        "name": "Vernal and Nevada Falls via Mist Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.72673696002307,
        "long": -119.53974603558228,
        "difficulty": "Hard",
        "length": "4.9 miles",
        "elevation": "1,000 ft",
        "route_type": "Out and Back",
        "description": "Try this 6.4-mile loop trail near Yosemite Valley, California. Generally considered a challenging route, it takes an average of 4 h 10 min to complete. This is a very popular area for hiking, so you'll likely encounter other people while exploring. The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views, Waterfalls",
        "activities": "Hiking, Photography",
        "suitability": "Kid Friendly, Wheelchair Friendly",
    },
    {
        "name": "Half Dome Via John Muir",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.73282,
        "long": -119.55778,
        "difficulty": "Hard",
        "length": "4.8 miles",
        "elevation": "4,800 ft",
        "route_type": "Out and Back",
        "description": "Try this 15.3-mile out-and-back trail near Yosemite Valley, California. Generally considered a challenging route. This is a very popular area for hiking and rock climbing, so you'll likely encounter other people while exploring. The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views, Cables",
        "activities": "Hiking, Rock Climbing",
        "suitability": "Experienced Hikers",
    },
    {
        "name": "Glacier Point Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.727820767402555,
        "long": -119.57426415228366,
        "difficulty": "Easy",
        "length": "1 mile",
        "elevation": "137 ft",
        "route_type": "Loop",
        "description": "Explore this 0.6-mile loop trail near Yosemite Valley, California. Generally considered an easy route, it takes an average of 19 min to complete. This is a very popular area for walking, so you'll likely encounter other people while exploring. The best times to visit this trail are June through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views, Yosemite Valley",
        "activities": "Hiking, Scenic Views",
        "suitability": "All Skill Levels,Family-friendly",
    },
    {
        "name": "Four Mile Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.73333912854748,
        "long": -119.58720630715618,
        "difficulty": "Hard",
        "length": "4.8 miles",
        "elevation": "3,200 ft",
        "route_type": "One Way",
        "description": "Get to know this 9.7-mile out-and-back trail near Yosemite Valley, California. Generally considered a challenging route, it takes an average of 6 h 23 min to complete. This is a very popular area for hiking, so you'll likely encounter other people while exploring. The best times to visit this trail are May through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views,Waterfalls",
        "activities": "Hiking, Scenic Views",
        "suitability": "Experienced Hikers",
    },
    {
        "name": "Upper Yosemite Falls Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.75832131220141,
        "long": -119.59695445246814,
        "difficulty": "Hard",
        "length": "7.2 miles",
        "elevation": "2,700 ft",
        "route_type": "Out and Back",
        "description": "Discover this 6.6-mile out-and-back trail near Yosemite Valley, California. Generally considered a challenging route, it takes an average of 5 h 21 min to complete. This is a very popular area for backpacking, camping, and hiking, so you'll likely encounter other people while exploring. The best times to visit this trail are April through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Waterfalls, Panoramic Views",
        "activities": "Hiking, Scenic Views",
        "suitability": "Experienced Hikers",
    },
    {
        "name": "Taft Point via Four Mile Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.714125934645736, 
        "long": -119.6042862786834,
        "difficulty": "Moderate",
        "length": "16.3 miles",
        "elevation": "4,845 ft",
        "route_type": "Loop",
        "description": "Try this 16.3-mile loop trail near Yosemite Valley, California. Generally considered a challenging route, it takes an average of 9 h 47 min to complete. This is a very popular area for hiking, so you'll likely encounter other people while exploring. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views, Granite Cliffs",
        "activities": "Hiking, Scenic Views",
        "suitability": "Intermediate",
    },
    {
        "name": "Mirror Lake Loop",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.74158833425448,
        "long": -119.55963895315217,
        "difficulty": "Easy",
        "length": "2.8 miles",
        "elevation": "100 ft",
        "route_type": "Loop",
        "description": "Check out this 4.2-mile loop trail near Government Camp, Oregon. Generally considered a moderately challenging route, it takes an average of 1 h 55 min to complete. This is a very popular area for backpacking, camping, and hiking, so you'll likely encounter other people while exploring. The best times to visit this trail are May through October. Dogs are welcome, but must be on a leash.",
        "attractions": "Lake Views, Scenic Reflections",
        "activities": "Hiking, Nature Walking",
        "suitability": "All Skill Levels, Family-friendly",
    },
    {
        "name": "Valley Loop Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.73739974895278,
        "long": -119.6081207327154,
        "difficulty": "Moderate",
        "length": "20.4 miles",
        "elevation": "500 ft",
        "route_type": "Loop",
        "description": "Experience this 20.4-mile loop trail near Yosemite Valley, California. Generally considered an easy route, it takes an average of 7 h 8 min to complete. This is a very popular area for hiking, snowshoeing, and running, so you'll likely encounter other people while exploring. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Scenic Views, Waterfalls",
        "activities": "Hiking, Scenic Views",
        "suitability": "Intermediate",
    },
    {
        "name": "Sentinel Dome Trail",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.7205060678489,
        "long": -119.58330436482736,
        "difficulty": "Moderate",
        "length": "2.2 miles",
        "elevation": "400 ft",
        "route_type": "Out and Back",
        "description": "Experience this 2.2-mile out-and-back trail near Yosemite Valley, California. Generally considered a moderately challenging route, it takes an average of 1 h 7 min to complete. This is a very popular area for hiking and running, so you'll likely encounter other people while exploring. The best times to visit this trail are June through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
        "attractions": "Panoramic Views, Granite Dome",
        "activities": "Hiking, Scenic Views",
        "suitability": "Intermediate",
    },
    {
        "name": "Pohono Trail (East to West)",
        "park": "Yosemite National Park",
        "city": "Yosemite Valley",
        "state": "California",
        "lat": 37.694824,
        "long": -119.642001,
        "difficulty": "Hard",
        "length": "12.2 miles",
        "elevation": "2,300 ft",
        "route_type": "Point to Point",
        "description": "Explore this 12.2-mile point-to-point trail near Yosemite Valley, California. Generally considered a challenging route, it takes an average of 7 h 6 min to complete. This is a popular trail for backpacking, camping, and hiking, but you can still enjoy some solitude during quieter times of day. The best times to visit this trail are June through October. You'll need to leave pups at home — dogs aren't allowed on this trail..",
        "attractions": "Panoramic Views, Rock Formations",
        "activities": "Hiking, Scenic Views",
        "suitability": "Experienced Hikers",
    },
    {
      "name": "Lady Bird Johnson Grove Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.307888, 
      "long": -124.023093,
      "difficulty": "Easy",
      "length": "1.4 miles",
      "elevation": "100 ft",
      "route_type": "Loop",
      "description": "Explore this 1.5-mile loop trail near Orick, California. Generally considered an easy route, it takes an average of 32 min to complete. This is a very popular area for hiking and running, so you'll likely encounter other people while exploring. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Old-Growth Redwoods, Nature",
      "activities": "Hiking, Nature Walking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
      "name": "Tall Trees Grove Loop Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.20838631027417, 
      "long": -123.99328724459889,
      "difficulty": "Moderate",
      "length": "3.6 miles",
      "elevation": "780 ft",
      "route_type": "Loop",
      "description": "Discover this 3.6-mile loop trail near Trinidad, California. Generally considered a moderately challenging route, it takes an average of 1 h 52 min to complete. This is a very popular area for hiking, running, and walking, so you'll likely encounter other people while exploring. The best times to visit this trail are March through October. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Ferns, Creek",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    {
      "name": "Coastal Trail and Yurok Loop",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.592979, 
      "long": -124.100951,
      "difficulty": "Moderate",
      "length": "9.5 miles",
      "elevation": "500 ft",
      "route_type": "Point to Point",
      "description": "Experience this 2.3-mile loop trail near Klamath, California. Generally considered an easy route, it takes an average of 48 min to complete. This is a popular trail for hiking, but you can still enjoy some solitude during quieter times of day. The best times to visit this trail are April through September. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Old-Growth Redwoods, Creek",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    {
      "name": "Trillium Falls Loop Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.316522, 
      "long": -124.045290,
      "difficulty": "Easy",
      "length": "2.8 miles",
      "elevation": "499 ft",
      "route_type": "Loop",
      "description": "Discover this 2.7-mile loop trail near Orick, California. Generally considered a moderately challenging route, it takes an average of 1 h 15 min to complete. This is a very popular area for hiking and walking, so you'll likely encounter other people while exploring. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Waterfall, Coastal Redwoods",
      "activities": "Hiking, Nature Walking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
      "name": "Enderts Beach via California Coastal Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.702896, 
      "long": -124.142049,
      "difficulty": "Moderate",
      "length": "1.3 miles",
      "elevation": "1730 ft",
      "route_type": "Out and Back",
      "description": "Enjoy this 1.3-mile out-and-back trail near Crescent City, California. Generally considered a moderately challenging route, it takes an average of 33 min to complete. This is a popular trail for backpacking, camping, and hiking, but you can still enjoy some solitude during quieter times of day. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Tall Redwoods, Nature",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    {
      "name": "Redwood Creek Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.25245384588262, 
      "long": -124.01248178004123,
      "difficulty": "Moderate",
      "length": "15.7 miles",
      "elevation": "1,118 ft",
      "route_type": "Out and Back",
      "description": "Get to know this 15.7-mile out-and-back trail near Orick, California. Generally considered a moderately challenging route, it takes an average of 5 h 38 min to complete. This is a very popular area for backpacking, fishing, and hiking, so you'll likely encounter other people while exploring. The best times to visit this trail are May through September. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Coastal Views, Creek",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    {
      "name": "Berry Glen and Lady Bird Grove Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.307038, 
      "long": -124.028963,
      "difficulty": "Moderate",
      "length": "6 miles",
      "elevation": "400 ft",
      "route_type": "Out and Back",
      "description": "Enjoy this 6.0-mile out-and-back trail near Orick, California. Generally considered a moderately challenging route, it takes an average of 3 h 4 min to complete. This is a popular trail for hiking, running, and walking, but you can still enjoy some solitude during quieter times of day. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Old-Growth Redwoods, Natural Landmark",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    {
      "name": "Skunk Cabbage Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.32232908850539, 
      "long": -124.07336894023881,
      "difficulty": "Moderate",
      "length": "7.4 miles",
      "elevation": "1,292 ft",
      "route_type": "Out and Back",
      "description": "Get to know this 7.4-mile out-and-back trail near Orick, California. Generally considered a moderately challenging route, it takes an average of 3 h 29 min to complete. This is a popular trail for birding, hiking, and running, but you can still enjoy some solitude during quieter times of day. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Fern Canyon, Coastal Views",
      "activities": "Hiking, Beach Exploration",
      "suitability": "Intermediate",
    },
    {
      "name": "Dolason Prairie Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.20333039734262, 
      "long": -123.9711772800651,
      "difficulty": "Moderate",
      "length": "9.1 miles",
      "elevation": "2,253 ft",
      "route_type": "Out and Back",
      "description": "Discover this 9.1-mile out-and-back trail near Orick, California. Generally considered a moderately challenging route, it takes an average of 4 h 59 min to complete. This trail is great for hiking and running, and it's unlikely you'll encounter many other people while exploring. The trail is open year-round and is beautiful to visit anytime. You'll need to leave pups at home — dogs aren't allowed on this trail.",
      "attractions": "Old-Growth Redwoods, Nature",
      "activities": "Hiking, Nature Walking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
      "name": "Flint Ridge Section Trail",
      "park": "Redwood National Park",
      "city": "Orick",
      "state": "California",
      "lat": 41.525065, 
      "long": -124.063658,
      "difficulty": "Moderate",
      "length": "8.4 miles",
      "elevation": "1,958 ft",
      "route_type": "Loop",
      "description": "This is a beautiful hike that has it all - redwood trees, lush forests full of ferns and interesting fungi, and grasslands. This is a great trail if you are looking for some solitude in nature. You will likely have this trail all to yourself. This trail can sometimes be overgrown, so downloading offline maps can help you navigate this trail. Be sure to bring bug spray.",
      "attractions": "Diverse Landscapes, Creek",
      "activities": "Hiking, Nature Walking",
      "suitability": "Intermediate",
    },
    # {
    #   "name": "General Sherman Tree Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5806,
    #   "long": -118.7511,
    #   "difficulty": "Easy",
    #   "length": "0.8 miles",
    #   "elevation": "200 ft",
    #   "route_type": "Loop",
    #   "description": "A popular trail leading to the General Sherman Tree, the largest known living tree on Earth, surrounded by giant sequoias.",
    #   "attractions": "Giant Sequoias, Natural Landmark",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "Moro Rock Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5477,
    #   "long": -118.7544,
    #   "difficulty": "Moderate",
    #   "length": "0.4 miles",
    #   "elevation": "300 ft",
    #   "route_type": "Out and Back",
    #   "description": "A steep trail leading to the top of Moro Rock, offering breathtaking panoramic views of the surrounding Sierra Nevada mountains.",
    #   "attractions": "Panoramic Views, Granite Dome",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Congress Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5621,
    #   "long": -118.7649,
    #   "difficulty": "Easy",
    #   "length": "2.0 miles",
    #   "elevation": "100 ft",
    #   "route_type": "Loop",
    #   "description": "A scenic loop trail that showcases the giants of the Giant Forest, including the President and Chief Sequoia trees.",
    #   "attractions": "Giant Sequoias, Natural Landmark",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "Lakes Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5822,
    #   "long": -118.7522,
    #   "difficulty": "Hard",
    #   "length": "13.2 miles",
    #   "elevation": "2,900 ft",
    #   "route_type": "Out and Back",
    #   "description": "A challenging trail that takes you to several beautiful alpine lakes, including Heather, Aster, and Pear Lakes.",
    #   "attractions": "Alpine Lakes, Mountain Views",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Experienced Hikers",
    # },
    # {
    #   "name": "Big Trees Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5542,
    #   "long": -118.7506,
    #   "difficulty": "Easy",
    #   "length": "0.6 miles",
    #   "elevation": "50 ft",
    #   "route_type": "Loop",
    #   "description": "A leisurely loop trail that provides an up-close experience with the magnificent giant sequoias of the Giant Forest.",
    #   "attractions": "Giant Sequoias, Nature",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "Alta Peak Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5948,
    #   "long": -118.6941,
    #   "difficulty": "Hard",
    #   "length": "14.2 miles",
    #   "elevation": "3,000 ft",
    #   "route_type": "Out and Back",
    #   "description": "A challenging trail that leads to the summit of Alta Peak, offering stunning panoramic views of the surrounding Sierra Nevada mountains.",
    #   "attractions": "Panoramic Views, Mountain Summit",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Experienced Hikers",
    # },
    # {
    #   "name": "Crescent Meadow Loop",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5628,
    #   "long": -118.7529,
    #   "difficulty": "Easy",
    #   "length": "1.6 miles",
    #   "elevation": "100 ft",
    #   "route_type": "Loop",
    #   "description": "A peaceful loop trail that winds through the scenic Crescent Meadow, offering picturesque views of the surrounding forest.",
    #   "attractions": "Meadow Views, Nature",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "High Sierra Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5781,
    #   "long": -118.6675,
    #   "difficulty": "Hard",
    #   "length": "72.2 miles",
    #   "elevation": "15,000 ft",
    #   "route_type": "Point to Point",
    #   "description": "An epic and demanding trail that traverses the Sierra Nevada, leading from Crescent Meadow to Mount Whitney.",
    #   "attractions": "Alpine Lakes, Mountain Views",
    #   "activities": "Hiking, Backpacking",
    #   "suitability": "Experienced Hikers",
    # },
    # {
    #   "name": "Muir Grove Trail",
    #   "park": "Kings Canyon National Park",
    #   "city": "Kings Canyon",
    #   "state": "California",
    #   "lat": 36.8394,
    #   "long": -118.8255,
    #   "difficulty": "Moderate",
    #   "length": "4.8 miles",
    #   "elevation": "800 ft",
    #   "route_type": "Out and Back",
    #   "description": "A scenic trail that leads to the tranquil Muir Grove, where you can marvel at the towering giant sequoias in solitude.",
    #   "attractions": "Giant Sequoias, Nature",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Tokopah Falls Trail",
    #   "park": "Sequoia National Park",
    #   "city": "Three Rivers",
    #   "state": "California",
    #   "lat": 36.5657,
    #   "long": -118.7252,
    #   "difficulty": "Moderate",
    #   "length": "4.6 miles",
    #   "elevation": "650 ft",
    #   "route_type": "Out and Back",
    #   "description": "A scenic trail that follows the Marble Fork of the Kaweah River and leads to the picturesque Tokopah Falls.",
    #   "attractions": "Waterfall, River Views",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Bear Gulch Cave Trail",
    #   "park": "Pinnacles National Park",
    #   "city": "Paicines",
    #   "state": "California",
    #   "lat": 36.4912,
    #   "long": -121.1594,
    #   "difficulty": "Easy",
    #   "length": "2.0 miles",
    #   "elevation": "200 ft",
    #   "route_type": "Loop",
    #   "description": "A unique trail that takes you through a series of talus caves, showcasing the park's geological wonders.",
    #   "attractions": "Caves, Rock Formations",
    #   "activities": "Hiking, Cave Exploration",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "High Peaks Trail",
    #   "park": "Pinnacles National Park",
    #   "city": "Paicines",
    #   "state": "California",
    #   "lat": 36.4834,
    #   "long": -121.1603,
    #   "difficulty": "Hard",
    #   "length": "5.5 miles",
    #   "elevation": "1,300 ft",
    #   "route_type": "Loop",
    #   "description": "A challenging trail that leads to the park's iconic high peaks, offering stunning panoramic views and unique rock formations.",
    #   "attractions": "Panoramic Views, Rock Formations",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Experienced Hikers",
    # },
    # {
    #   "name": "Condor Gulch Trail",
    #   "park": "Pinnacles National Park",
    #   "city": "Paicines",
    #   "state": "California",
    #   "lat": 36.4955,
    #   "long": -121.1555,
    #   "difficulty": "Moderate",
    #   "length": "3.0 miles",
    #   "elevation": "800 ft",
    #   "route_type": "Out and Back",
    #   "description": "A scenic trail that takes you to a viewpoint overlooking the majestic Pinnacles rock formations and the surrounding valleys.",
    #   "attractions": "Panoramic Views, Rock Formations",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Bear Gulch Reservoir Trail",
    #   "park": "Pinnacles National Park",
    #   "city": "Paicines",
    #   "state": "California",
    #   "lat": 36.4919,
    #   "long": -121.1589,
    #   "difficulty": "Easy",
    #   "length": "1.5 miles",
    #   "elevation": "100 ft",
    #   "route_type": "Loop",
    #   "description": "A peaceful trail that leads to Bear Gulch Reservoir, offering serene views and opportunities for wildlife sighting.",
    #   "attractions": "Reservoir, Nature",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "Balconies Cliffs Trail",
    #   "park": "Pinnacles National Park",
    #   "city": "Paicines",
    #   "state": "California",
    #   "lat": 36.4900,
    #   "long": -121.1639,
    #   "difficulty": "Moderate",
    #   "length": "2.4 miles",
    #   "elevation": "500 ft",
    #   "route_type": "Loop",
    #   "description": "A scenic trail that leads you along the towering Balconies Cliffs, offering breathtaking views and unique rock formations.",
    #   "attractions": "Panoramic Views, Rock Formations",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Bumpass Hell Trail",
    #   "park": "Lassen Volcanic National Park",
    #   "city": "Mineral",
    #   "state": "California",
    #   "lat": 40.4678,
    #   "long": -121.5134,
    #   "difficulty": "Moderate",
    #   "length": "3.0 miles",
    #   "elevation": "400 ft",
    #   "route_type": "Out and Back",
    #   "description": "A unique trail that takes you to the famous Bumpass Hell, a hydrothermal area known for its boiling mud pots and steam vents.",
    #   "attractions": "Hydrothermal Features, Geothermal Activity",
    #   "activities": "Hiking, Sightseeing",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Cinder Cone Trail",
    #   "park": "Lassen Volcanic National Park",
    #   "city": "Mineral",
    #   "state": "California",
    #   "lat": 40.5465,
    #   "long": -121.4002,
    #   "difficulty": "Moderate",
    #   "length": "4.0 miles",
    #   "elevation": "800 ft",
    #   "route_type": "Out and Back",
    #   "description": "A scenic trail that leads to the top of Cinder Cone, providing panoramic views of the surrounding volcanic landscape.",
    #   "attractions": "Volcanic Cone, Panoramic Views",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Intermediate",
    # },
    # {
    #   "name": "Kings Creek Falls Trail",
    #   "park": "Lassen Volcanic National Park",
    #   "city": "Mineral",
    #   "state": "California",
    #   "lat": 40.5033,
    #   "long": -121.5321,
    #   "difficulty": "Easy",
    #   "length": "2.8 miles",
    #   "elevation": "300 ft",
    #   "route_type": "Out and Back",
    #   "description": "A beautiful trail that leads to the picturesque Kings Creek Falls, cascading over a basalt cliff in a tranquil setting.",
    #   "attractions": "Waterfall, Scenic Views",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
    # {
    #   "name": "Lassen Peak Trail",
    #   "park": "Lassen Volcanic National Park",
    #   "city": "Mineral",
    #   "state": "California",
    #   "lat": 40.4882,
    #   "long": -121.5059,
    #   "difficulty": "Hard",
    #   "length": "5.0 miles",
    #   "elevation": "2,000 ft",
    #   "route_type": "Out and Back",
    #   "description": "A challenging trail that leads to the summit of Lassen Peak, providing sweeping views of the park's volcanic landscape.",
    #   "attractions": "Volcanic Summit, Panoramic Views",
    #   "activities": "Hiking, Scenic Views",
    #   "suitability": "Experienced Hikers",
    # },
    # {
    #   "name": "Manzanita Lake Loop Trail",
    #   "park": "Lassen Volcanic National Park",
    #   "city": "Mineral",
    #   "state": "California",
    #   "lat": 40.5524,
    #   "long": -121.5590,
    #   "difficulty": "Easy",
    #   "length": "1.6 miles",
    #   "elevation": "50 ft",
    #   "route_type": "Loop",
    #   "description": "A leisurely loop trail that offers serene views of Manzanita Lake and the surrounding forest, perfect for a peaceful stroll.",
    #   "attractions": "Lake Views, Nature",
    #   "activities": "Hiking, Nature Walking",
    #   "suitability": "All Skill Levels, Family-friendly",
    # },
]


# @with_appcontext
def seed_trails(app):
    with app.app_context():
        for data in seed_data:
            trail = Trail(**data)
            db.session.add(trail)

        db.session.commit()


# @with_appcontext
def undo_trails(app):
    with app.app_context():
        if environment == "production":
            db.session.execute(
                f"TRUNCATE table {SCHEMA}.trails RESTART IDENTITY CASCADE;"
            )
        else:
            db.session.execute(text("DELETE FROM trails"))

        db.session.commit()
