from app.models import db, Trail, environment, SCHEMA
from sqlalchemy.sql import text

seed_data = [
    {
      "name": "Ed Levin County Park Loop",
      "park": "Ed Levin County Park",
      "city": "Milpitas",
      "state": "California",
      "lat": 37.4841,
      "long": -121.8184,
      "difficulty": "Easy",
      "length": 3.7,
      "elevation": "500 ft",
      "route_type": "Loop",
      "description": "A scenic loop trail with beautiful views of Milpitas and the surrounding hills.",
      "attractions": "City Views, Wildflowers",
      "activities": "Hiking, Picnicking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
      "name": "Calaveras Ridge Trail",
      "park": "Calaveras Reservoir",
      "city": "Milpitas",
      "state": "California",
      "lat": 37.5374,
      "long": -121.8197,
      "difficulty": "Moderate",
      "length": "6.4 miles",
      "elevation": "1,200 ft",
      "route_type": "Out and Back",
      "description": "A scenic trail along the ridge of Calaveras Reservoir with panoramic views of the water and surrounding hills.",
      "attractions": "Reservoir Views, Wildlife",
      "activities": "Hiking, Birdwatching",
      "suitability": "Intermediate",
    },
    {
      "name": "Mission Peak Trail",
      "park": "Mission Peak Regional Preserve",
      "city": "Fremont",
      "state": "California",
      "lat": 37.5022,
      "long": -121.9152,
      "difficulty": "Hard",
      "length": "5.6 miles",
      "elevation": "2,000 ft",
      "route_type": "Out and Back",
      "description": "A popular trail leading to the iconic Mission Peak summit with stunning views of the Bay Area.",
      "attractions": "Panoramic Views, Wildflowers",
      "activities": "Hiking, Trail Running",
      "suitability": "Experienced Hikers",
    },
    {
      "name": "Coyote Creek Trail",
      "park": "Coyote Creek Trail",
      "city": "Milpitas",
      "state": "California",
      "lat": 37.4439,
      "long": -121.8869,
      "difficulty": "Easy",
      "length": "15.6 miles",
      "elevation": "100 ft",
      "route_type": "Point to Point",
      "description": "A peaceful trail following the scenic Coyote Creek with opportunities for birdwatching and nature observation.",
      "attractions": "Creek Views, Wildlife",
      "activities": "Hiking, Biking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
      "name": "Berryessa Creek Trail",
      "park": "Berryessa Creek Park",
      "city": "Milpitas",
      "state": "California",
      "lat": 37.4507,
      "long": -121.8543,
      "difficulty": "Easy",
      "length": "2.5 miles",
      "elevation": "50 ft",
      "route_type": "Out and Back",
      "description": "A pleasant trail along Berryessa Creek with serene views and opportunities for wildlife spotting.",
      "attractions": "Creek Views, Wildlife",
      "activities": "Hiking, Nature Walking",
      "suitability": "All Skill Levels, Family-friendly",
    },
    {
        "name": "Alum Rock Park Loop",
        "park": "Alum Rock Park",
        "city": "San Jose",
        "state": "California",
        "lat": 37.3716,
        "long": -121.8283,
        "difficulty": "Moderate",
        "length": "6.2 miles",
        "elevation": "1,000 ft",
        "route_type": "Loop",
        "description": "A scenic loop trail within Alum Rock Park with varied terrain and beautiful views.",
        "attractions": "Park Views, Wildlife",
        "activities": "Hiking, Nature Watching",
        "suitability": "Intermediate",
      },
      {
        "name": "Sierra Vista Open Space Preserve",
        "park": "Sierra Vista Open Space Preserve",
        "city": "San Jose",
        "state": "California",
        "lat": 37.3783,
        "long": -121.8173,
        "difficulty": "Moderate",
        "length": "3.5 miles",
        "elevation": "600 ft",
        "route_type": "Loop",
        "description": "A nature preserve with a scenic loop trail offering sweeping views of the surrounding hills.",
        "attractions": "Hill Views, Wildflowers",
        "activities": "Hiking, Nature Walking",
        "suitability": "Intermediate",
      },
      {
        "name": "Coyote Hills Regional Park",
        "park": "Coyote Hills Regional Park",
        "city": "Fremont",
        "state": "California",
        "lat": 37.5549,
        "long": -122.0717,
        "difficulty": "Easy",
        "length": "3.1 miles",
        "elevation": "100 ft",
        "route_type": "Loop",
        "description": "A scenic park with trails that explore marshlands, offering opportunities for birdwatching and wildlife observation.",
        "attractions": "Marsh Views, Birds",
        "activities": "Hiking, Birdwatching",
        "suitability": "All Skill Levels, Family-friendly",
      },
      {
        "name": "Mount Hamilton Grandview Trail",
        "park": "Mount Hamilton",
        "city": "San Jose",
        "state": "California",
        "lat": 37.3431,
        "long": -121.6382,
        "difficulty": "Moderate",
        "length": "9.2 miles",
        "elevation": "1,300 ft",
        "route_type": "Out and Back",
        "description": "A trail that leads to a panoramic viewpoint atop Mount Hamilton, offering stunning vistas of the surrounding area.",
        "attractions": "Panoramic Views, Mountain Summit",
        "activities": "Hiking, Scenic Views",
        "suitability": "Intermediate",
      },
      {
        "name": "Coyote Peak Trail",
        "park": "Santa Teresa County Park",
        "city": "San Jose",
        "state": "California",
        "lat": 37.2197,
        "long": -121.7694,
        "difficulty": "Moderate",
        "length": "4.6 miles",
        "elevation": "1,100 ft",
        "route_type": "Out and Back",
        "description": "A trail that ascends to the summit of Coyote Peak, providing panoramic views of the Santa Clara Valley.",
        "attractions": "Valley Views, Wildflowers",
        "activities": "Hiking, Nature Watching",
        "suitability": "Intermediate",
      },
    #   {
    #     "name": "Stevens Creek Trail",
    #     "park": "Stevens Creek County Park",
    #     "city": "Cupertino",
    #     "state": "California",
    #     "lat": 37.3339,
    #     "long": -122.0806,
    #     "difficulty": "Easy",
    #     "length": "5.3 miles",
    #     "elevation": "100 ft",
    #     "route_type": "Out and Back",
    #     "description": "A scenic trail following the meandering course of Stevens Creek, surrounded by natural beauty.",
    #     "attractions": "Creek Views, Wildlife",
    #     "activities": "Hiking, Biking",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Almaden Quicksilver County Park",
    #     "park": "Almaden Quicksilver County Park",
    #     "city": "San Jose",
    #     "state": "California",
    #     "lat": 37.1732,
    #     "long": -121.8437,
    #     "difficulty": "Moderate",
    #     "length": "9.8 miles",
    #     "elevation": "1,200 ft",
    #     "route_type": "Loop",
    #     "description": "A historic park with trails that wind through former mercury mines and provide scenic views of the surrounding hills.",
    #     "attractions": "Mining History, Scenic Views",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Almaden Lake Park Loop",
    #     "park": "Almaden Lake Park",
    #     "city": "San Jose",
    #     "state": "California",
    #     "lat": 37.2199,
    #     "long": -121.8628,
    #     "difficulty": "Easy",
    #     "length": "1.4 miles",
    #     "elevation": "30 ft",
    #     "route_type": "Loop",
    #     "description": "A pleasant loop trail around Almaden Lake, offering serene water views and opportunities for picnicking.",
    #     "attractions": "Lake Views, Picnic Areas",
    #     "activities": "Hiking, Picnicking",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Coyote Creek Trail - Anderson Lake",
    #     "park": "Anderson Lake County Park",
    #     "city": "Morgan Hill",
    #     "state": "California",
    #     "lat": 37.1411,
    #     "long": -121.6519,
    #     "difficulty": "Easy",
    #     "length": "5.6 miles",
    #     "elevation": "50 ft",
    #     "route_type": "Out and Back",
    #     "description": "A scenic trail along Coyote Creek with views of Anderson Lake, providing opportunities for wildlife observation.",
    #     "attractions": "Creek Views, Lake Views",
    #     "activities": "Hiking, Nature Watching",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Rancho San Antonio County Park",
    #     "park": "Rancho San Antonio County Park",
    #     "city": "Los Altos",
    #     "state": "California",
    #     "lat": 37.3332,
    #     "long": -122.0856,
    #     "difficulty": "Moderate",
    #     "length": "6.8 miles",
    #     "elevation": "800 ft",
    #     "route_type": "Loop",
    #     "description": "A beautiful park with trails that traverse through rolling hills, showcasing scenic vistas and diverse wildlife.",
    #     "attractions": "Hill Views, Wildlife",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Vargas Plateau Regional Park",
    #     "park": "Vargas Plateau Regional Park",
    #     "city": "Fremont",
    #     "state": "California",
    #     "lat": 37.5184,
    #     "long": -121.8769,
    #     "difficulty": "Moderate",
    #     "length": "4.5 miles",
    #     "elevation": "600 ft",
    #     "route_type": "Loop",
    #     "description": "A picturesque park with trails that offer panoramic views of the surrounding landscapes and wildflower meadows.",
    #     "attractions": "Scenic Views, Wildflowers",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Pleasanton Ridge Regional Park",
    #     "park": "Pleasanton Ridge Regional Park",
    #     "city": "Pleasanton",
    #     "state": "California",
    #     "lat": 37.6226,
    #     "long": -121.9006,
    #     "difficulty": "Moderate",
    #     "length": "9.3 miles",
    #     "elevation": "1,200 ft",
    #     "route_type": "Loop",
    #     "description": "A vast park with a network of trails offering panoramic views of the East Bay and opportunities for wildlife sighting.",
    #     "attractions": "Scenic Views, Wildlife",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Black Mountain Trail",
    #     "park": "Black Mountain Open Space Preserve",
    #     "city": "Los Altos",
    #     "state": "California",
    #     "lat": 37.3271,
    #     "long": -122.1622,
    #     "difficulty": "Hard",
    #     "length": "9.5 miles",
    #     "elevation": "2,300 ft",
    #     "route_type": "Out and Back",
    #     "description": "A challenging trail that leads to the summit of Black Mountain, providing expansive views of the Bay Area.",
    #     "attractions": "Panoramic Views, Mountain Summit",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Uvas Canyon Waterfall Loop Trail",
    #     "park": "Uvas Canyon County Park",
    #     "city": "Morgan Hill",
    #     "state": "California",
    #     "lat": 37.0621,
    #     "long": -121.8102,
    #     "difficulty": "Moderate",
    #     "length": "4.9 miles",
    #     "elevation": "600 ft",
    #     "route_type": "Loop",
    #     "description": "A scenic trail that explores the lush Uvas Canyon with multiple picturesque waterfalls along the way.",
    #     "attractions": "Waterfalls, Redwoods",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Mount Diablo Summit Trail",
    #     "park": "Mount Diablo State Park",
    #     "city": "Clayton",
    #     "state": "California",
    #     "lat": 37.8815,
    #     "long": -121.9146,
    #     "difficulty": "Hard",
    #     "length": "6.8 miles",
    #     "elevation": "2,200 ft",
    #     "route_type": "Out and Back",
    #     "description": "A challenging trail that leads to the summit of Mount Diablo, offering breathtaking views of the surrounding area.",
    #     "attractions": "Panoramic Views, Mountain Summit",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Mist Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7349,
    #     "long": -119.5336,
    #     "difficulty": "Moderate",
    #     "length": "3 miles",
    #     "elevation": "1,000 ft",
    #     "route_type": "Out and Back",
    #     "description": "A popular trail that takes you up close to Vernal and Nevada Falls, offering breathtaking views and misty experiences.",
    #     "attractions": "Waterfalls, Panoramic Views",
    #     "activities": "Hiking, Photography",
    #     "suitability": "Kid Friendly, Wheelchair Friendly",
    #   },
    #   {
    #     "name": "Half Dome Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7395,
    #     "long": -119.5350,
    #     "difficulty": "Hard",
    #     "length": "14.2 miles",
    #     "elevation": "4,800 ft",
    #     "route_type": "Out and Back",
    #     "description": "An iconic and challenging trail that culminates with a thrilling ascent up the famous Half Dome.",
    #     "attractions": "Panoramic Views, Cables",
    #     "activities": "Hiking, Rock Climbing",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Glacier Point Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7304,
    #     "long": -119.5740,
    #     "difficulty": "Easy",
    #     "length": "0.5 miles",
    #     "elevation": "100 ft",
    #     "route_type": "Out and Back",
    #     "description": "A short trail leading to Glacier Point, offering stunning panoramic views of Yosemite Valley and its iconic landmarks.",
    #     "attractions": "Panoramic Views, Yosemite Valley",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "All Skill Levels,Family-friendly",
    #   },
    #   {
    #     "name": "Four Mile Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7283,
    #     "long": -119.5928,
    #     "difficulty": "Hard",
    #     "length": "4.8 miles",
    #     "elevation": "3,200 ft",
    #     "route_type": "One Way",
    #     "description": "A challenging trail that ascends from Yosemite Valley to Glacier Point, offering spectacular views along the way.",
    #     "attractions": "Panoramic Views,Waterfalls",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Upper Yosemite Falls Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7555,
    #     "long": -119.5972,
    #     "difficulty": "Hard",
    #     "length": "7.2 miles",
    #     "elevation": "2,700 ft",
    #     "route_type": "Out and Back",
    #     "description": "A strenuous trail leading to the top of Yosemite Falls, offering breathtaking views of the valley and the falls.",
    #     "attractions": "Waterfalls, Panoramic Views",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Taft Point Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7196,
    #     "long": -119.5789,
    #     "difficulty": "Moderate",
    #     "length": "2.2 miles",
    #     "elevation": "500 ft",
    #     "route_type": "Loop",
    #     "description": "A scenic loop trail that leads to Taft Point, offering breathtaking views of El Capitan and Yosemite Valley.",
    #     "attractions": "Panoramic Views, Granite Cliffs",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Mirror Lake Loop",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7482,
    #     "long": -119.5765,
    #     "difficulty": "Easy",
    #     "length": "2.8 miles",
    #     "elevation": "100 ft",
    #     "route_type": "Loop",
    #     "description": "A peaceful loop trail around Mirror Lake, offering serene reflections of the surrounding cliffs and peaks.",
    #     "attractions": "Lake Views, Scenic Reflections",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Valley Loop Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7469,
    #     "long": -119.5898,
    #     "difficulty": "Moderate",
    #     "length": "10.4 miles",
    #     "elevation": "500 ft",
    #     "route_type": "Loop",
    #     "description": "A picturesque loop trail that explores the highlights of Yosemite Valley, offering iconic views and diverse scenery.",
    #     "attractions": "Scenic Views, Waterfalls",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Sentinel Dome Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.7279,
    #     "long": -119.6051,
    #     "difficulty": "Moderate",
    #     "length": "2.2 miles",
    #     "elevation": "400 ft",
    #     "route_type": "Out and Back",
    #     "description": "A rewarding trail leading to Sentinel Dome, offering stunning panoramic views of Yosemite Valley and surrounding peaks.",
    #     "attractions": "Panoramic Views, Granite Dome",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Pohono Trail",
    #     "park": "Yosemite National Park",
    #     "city": "Yosemite Valley",
    #     "state": "California",
    #     "lat": 37.6867,
    #     "long": -119.6619,
    #     "difficulty": "Hard",
    #     "length": "13.8 miles",
    #     "elevation": "2,300 ft",
    #     "route_type": "Point to Point",
    #     "description": "A challenging trail that spans from Glacier Point to Tunnel View, offering magnificent vistas of Yosemite Valley.",
    #     "attractions": "Panoramic Views, Rock Formations",
    #     "activities": "Hiking, Scenic Views",
    #     "suitability": "Experienced Hikers",
    #   },
    #   {
    #     "name": "Lady Bird Johnson Grove Trail",
    #     "park": "Redwood National and State Parks",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3067,
    #     "long": -124.0114,
    #     "difficulty": "Easy",
    #     "length": "1.4 miles",
    #     "elevation": "100 ft",
    #     "route_type": "Loop",
    #     "description": "A beautiful loop trail that meanders through the old-growth redwood forest, offering a peaceful and serene experience.",
    #     "attractions": "Old-Growth Redwoods, Nature",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Fern Canyon Trail",
    #     "park": "Prairie Creek Redwoods State Park",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3312,
    #     "long": -124.0165,
    #     "difficulty": "Moderate",
    #     "length": "1.1 miles",
    #     "elevation": "100 ft",
    #     "route_type": "Loop",
    #     "description": "A unique trail that takes you through a lush canyon filled with ferns and moss-covered walls, creating a magical ambiance.",
    #     "attractions": "Ferns, Creek",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "James Irvine Trail",
    #     "park": "Prairie Creek Redwoods State Park",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3303,
    #     "long": -124.0163,
    #     "difficulty": "Moderate",
    #     "length": "9.5 miles",
    #     "elevation": "500 ft",
    #     "route_type": "Point to Point",
    #     "description": "A scenic trail that traverses through the ancient redwood forest, offering a mesmerizing experience in nature's grandeur.",
    #     "attractions": "Old-Growth Redwoods, Creek",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Trillium Falls Loop Trail",
    #     "park": "Redwood National and State Parks",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3273,
    #     "long": -124.0433,
    #     "difficulty": "Easy",
    #     "length": "2.8 miles",
    #     "elevation": "200 ft",
    #     "route_type": "Loop",
    #     "description": "A serene loop trail that leads to Trillium Falls, surrounded by beautiful coastal redwoods and lush vegetation.",
    #     "attractions": "Waterfall, Coastal Redwoods",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "All Skill Levels, Family-friendly",
    #   },
    #   {
    #     "name": "Tall Trees Grove Trail",
    #     "park": "Redwood National and State Parks",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3171,
    #     "long": -124.0579,
    #     "difficulty": "Moderate",
    #     "length": "4.5 miles",
    #     "elevation": "600 ft",
    #     "route_type": "Out and Back",
    #     "description": "A stunning trail leading to the majestic Tall Trees Grove, where you'll encounter some of the tallest trees on Earth.",
    #     "attractions": "Tall Redwoods, Nature",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Damnation Creek Trail",
    #     "park": "Del Norte Coast Redwoods State Park",
    #     "city": "Crescent City",
    #     "state": "California",
    #     "lat": 41.7346,
    #     "long": -124.0916,
    #     "difficulty": "Moderate",
    #     "length": "4.6 miles",
    #     "elevation": "1,000 ft",
    #     "route_type": "Out and Back",
    #     "description": "A challenging trail that descends through a lush canyon to the rugged Pacific coastline, offering breathtaking views.",
    #     "attractions": "Coastal Views, Creek",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Boy Scout Tree Trail",
    #     "park": "Jedediah Smith Redwoods State Park",
    #     "city": "Crescent City",
    #     "state": "California",
    #     "lat": 41.8041,
    #     "long": -124.0645,
    #     "difficulty": "Moderate",
    #     "length": "5.4 miles",
    #     "elevation": "400 ft",
    #     "route_type": "Out and Back",
    #     "description": "A scenic trail that leads to the iconic Boy Scout Tree, passing through an enchanting old-growth redwood forest.",
    #     "attractions": "Old-Growth Redwoods, Natural Landmark",
    #     "activities": "Hiking, Nature Walking",
    #     "suitability": "Intermediate",
    #   },
    #   {
    #     "name": "Fern Canyon to Gold Bluffs Beach",
    #     "park": "Prairie Creek Redwoods State Park",
    #     "city": "Orick",
    #     "state": "California",
    #     "lat": 41.3492,
    #     "long": -124.0321,
    #     "difficulty": "Moderate",
    #     "length": "7.8 miles",
    #     "elevation": "200 ft",
    #     "route_type": "Point to Point",
    #     "description": "A scenic trail that combines the enchanting Fern Canyon with the picturesque Gold Bluffs Beach, showcasing the best of the coast and the redwoods.",
    #     "attractions": "Fern Canyon, Coastal Views",
    #     "activities": "Hiking, Beach Exploration",
    #     "suitability": "Intermediate",
    #   },
      # {
      #   "name": "Stout Memorial Grove Trail",
      #   "park": "Jedediah Smith Redwoods State Park",
      #   "city": "Crescent City",
      #   "state": "California",
      #   "lat": 41.8199,
      #   "long": -124.0914,
      #   "difficulty": "Easy",
      #   "length": "0.6 miles",
      #   "elevation": "50 ft",
      #   "route_type": "Loop",
      #   "description": "A short and peaceful loop trail that immerses you in the tranquility of an ancient redwood grove, offering a serene nature experience.",
      #   "attractions": "Old-Growth Redwoods, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Nickel Creek Trail",
      #   "park": "Del Norte Coast Redwoods State Park",
      #   "city": "Crescent City",
      #   "state": "California",
      #   "lat": 41.8276,
      #   "long": -124.1215,
      #   "difficulty": "Moderate",
      #   "length": "8.6 miles",
      #   "elevation": "800 ft",
      #   "route_type": "Loop",
      #   "description": "A hidden gem of a trail that meanders through diverse landscapes, including forests, meadows, and creeks, providing a unique and immersive hiking experience.",
      #   "attractions": "Diverse Landscapes, Creek",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "General Sherman Tree Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5806,
      #   "long": -118.7511,
      #   "difficulty": "Easy",
      #   "length": "0.8 miles",
      #   "elevation": "200 ft",
      #   "route_type": "Loop",
      #   "description": "A popular trail leading to the General Sherman Tree, the largest known living tree on Earth, surrounded by giant sequoias.",
      #   "attractions": "Giant Sequoias, Natural Landmark",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Moro Rock Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5477,
      #   "long": -118.7544,
      #   "difficulty": "Moderate",
      #   "length": "0.4 miles",
      #   "elevation": "300 ft",
      #   "route_type": "Out and Back",
      #   "description": "A steep trail leading to the top of Moro Rock, offering breathtaking panoramic views of the surrounding Sierra Nevada mountains.",
      #   "attractions": "Panoramic Views, Granite Dome",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Congress Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5621,
      #   "long": -118.7649,
      #   "difficulty": "Easy",
      #   "length": "2.0 miles",
      #   "elevation": "100 ft",
      #   "route_type": "Loop",
      #   "description": "A scenic loop trail that showcases the giants of the Giant Forest, including the President and Chief Sequoia trees.",
      #   "attractions": "Giant Sequoias, Natural Landmark",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Lakes Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5822,
      #   "long": -118.7522,
      #   "difficulty": "Hard",
      #   "length": "13.2 miles",
      #   "elevation": "2,900 ft",
      #   "route_type": "Out and Back",
      #   "description": "A challenging trail that takes you to several beautiful alpine lakes, including Heather, Aster, and Pear Lakes.",
      #   "attractions": "Alpine Lakes, Mountain Views",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Experienced Hikers",
      # },
      # {
      #   "name": "Big Trees Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5542,
      #   "long": -118.7506,
      #   "difficulty": "Easy",
      #   "length": "0.6 miles",
      #   "elevation": "50 ft",
      #   "route_type": "Loop",
      #   "description": "A leisurely loop trail that provides an up-close experience with the magnificent giant sequoias of the Giant Forest.",
      #   "attractions": "Giant Sequoias, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Alta Peak Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5948,
      #   "long": -118.6941,
      #   "difficulty": "Hard",
      #   "length": "14.2 miles",
      #   "elevation": "3,000 ft",
      #   "route_type": "Out and Back",
      #   "description": "A challenging trail that leads to the summit of Alta Peak, offering stunning panoramic views of the surrounding Sierra Nevada mountains.",
      #   "attractions": "Panoramic Views, Mountain Summit",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Experienced Hikers",
      # },
      # {
      #   "name": "Crescent Meadow Loop",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5628,
      #   "long": -118.7529,
      #   "difficulty": "Easy",
      #   "length": "1.6 miles",
      #   "elevation": "100 ft",
      #   "route_type": "Loop",
      #   "description": "A peaceful loop trail that winds through the scenic Crescent Meadow, offering picturesque views of the surrounding forest.",
      #   "attractions": "Meadow Views, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "High Sierra Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5781,
      #   "long": -118.6675,
      #   "difficulty": "Hard",
      #   "length": "72.2 miles",
      #   "elevation": "15,000 ft",
      #   "route_type": "Point to Point",
      #   "description": "An epic and demanding trail that traverses the Sierra Nevada, leading from Crescent Meadow to Mount Whitney.",
      #   "attractions": "Alpine Lakes, Mountain Views",
      #   "activities": "Hiking, Backpacking",
      #   "suitability": "Experienced Hikers",
      # },
      # {
      #   "name": "Muir Grove Trail",
      #   "park": "Kings Canyon National Park",
      #   "city": "Kings Canyon",
      #   "state": "California",
      #   "lat": 36.8394,
      #   "long": -118.8255,
      #   "difficulty": "Moderate",
      #   "length": "4.8 miles",
      #   "elevation": "800 ft",
      #   "route_type": "Out and Back",
      #   "description": "A scenic trail that leads to the tranquil Muir Grove, where you can marvel at the towering giant sequoias in solitude.",
      #   "attractions": "Giant Sequoias, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Tokopah Falls Trail",
      #   "park": "Sequoia National Park",
      #   "city": "Three Rivers",
      #   "state": "California",
      #   "lat": 36.5657,
      #   "long": -118.7252,
      #   "difficulty": "Moderate",
      #   "length": "4.6 miles",
      #   "elevation": "650 ft",
      #   "route_type": "Out and Back",
      #   "description": "A scenic trail that follows the Marble Fork of the Kaweah River and leads to the picturesque Tokopah Falls.",
      #   "attractions": "Waterfall, River Views",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Bear Gulch Cave Trail",
      #   "park": "Pinnacles National Park",
      #   "city": "Paicines",
      #   "state": "California",
      #   "lat": 36.4912,
      #   "long": -121.1594,
      #   "difficulty": "Easy",
      #   "length": "2.0 miles",
      #   "elevation": "200 ft",
      #   "route_type": "Loop",
      #   "description": "A unique trail that takes you through a series of talus caves, showcasing the park's geological wonders.",
      #   "attractions": "Caves, Rock Formations",
      #   "activities": "Hiking, Cave Exploration",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "High Peaks Trail",
      #   "park": "Pinnacles National Park",
      #   "city": "Paicines",
      #   "state": "California",
      #   "lat": 36.4834,
      #   "long": -121.1603,
      #   "difficulty": "Hard",
      #   "length": "5.5 miles",
      #   "elevation": "1,300 ft",
      #   "route_type": "Loop",
      #   "description": "A challenging trail that leads to the park's iconic high peaks, offering stunning panoramic views and unique rock formations.",
      #   "attractions": "Panoramic Views, Rock Formations",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Experienced Hikers",
      # },
      # {
      #   "name": "Condor Gulch Trail",
      #   "park": "Pinnacles National Park",
      #   "city": "Paicines",
      #   "state": "California",
      #   "lat": 36.4955,
      #   "long": -121.1555,
      #   "difficulty": "Moderate",
      #   "length": "3.0 miles",
      #   "elevation": "800 ft",
      #   "route_type": "Out and Back",
      #   "description": "A scenic trail that takes you to a viewpoint overlooking the majestic Pinnacles rock formations and the surrounding valleys.",
      #   "attractions": "Panoramic Views, Rock Formations",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Bear Gulch Reservoir Trail",
      #   "park": "Pinnacles National Park",
      #   "city": "Paicines",
      #   "state": "California",
      #   "lat": 36.4919,
      #   "long": -121.1589,
      #   "difficulty": "Easy",
      #   "length": "1.5 miles",
      #   "elevation": "100 ft",
      #   "route_type": "Loop",
      #   "description": "A peaceful trail that leads to Bear Gulch Reservoir, offering serene views and opportunities for wildlife sighting.",
      #   "attractions": "Reservoir, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Balconies Cliffs Trail",
      #   "park": "Pinnacles National Park",
      #   "city": "Paicines",
      #   "state": "California",
      #   "lat": 36.4900,
      #   "long": -121.1639,
      #   "difficulty": "Moderate",
      #   "length": "2.4 miles",
      #   "elevation": "500 ft",
      #   "route_type": "Loop",
      #   "description": "A scenic trail that leads you along the towering Balconies Cliffs, offering breathtaking views and unique rock formations.",
      #   "attractions": "Panoramic Views, Rock Formations",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Bumpass Hell Trail",
      #   "park": "Lassen Volcanic National Park",
      #   "city": "Mineral",
      #   "state": "California",
      #   "lat": 40.4678,
      #   "long": -121.5134,
      #   "difficulty": "Moderate",
      #   "length": "3.0 miles",
      #   "elevation": "400 ft",
      #   "route_type": "Out and Back",
      #   "description": "A unique trail that takes you to the famous Bumpass Hell, a hydrothermal area known for its boiling mud pots and steam vents.",
      #   "attractions": "Hydrothermal Features, Geothermal Activity",
      #   "activities": "Hiking, Sightseeing",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Cinder Cone Trail",
      #   "park": "Lassen Volcanic National Park",
      #   "city": "Mineral",
      #   "state": "California",
      #   "lat": 40.5465,
      #   "long": -121.4002,
      #   "difficulty": "Moderate",
      #   "length": "4.0 miles",
      #   "elevation": "800 ft",
      #   "route_type": "Out and Back",
      #   "description": "A scenic trail that leads to the top of Cinder Cone, providing panoramic views of the surrounding volcanic landscape.",
      #   "attractions": "Volcanic Cone, Panoramic Views",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Intermediate",
      # },
      # {
      #   "name": "Kings Creek Falls Trail",
      #   "park": "Lassen Volcanic National Park",
      #   "city": "Mineral",
      #   "state": "California",
      #   "lat": 40.5033,
      #   "long": -121.5321,
      #   "difficulty": "Easy",
      #   "length": "2.8 miles",
      #   "elevation": "300 ft",
      #   "route_type": "Out and Back",
      #   "description": "A beautiful trail that leads to the picturesque Kings Creek Falls, cascading over a basalt cliff in a tranquil setting.",
      #   "attractions": "Waterfall, Scenic Views",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
      # {
      #   "name": "Lassen Peak Trail",
      #   "park": "Lassen Volcanic National Park",
      #   "city": "Mineral",
      #   "state": "California",
      #   "lat": 40.4882,
      #   "long": -121.5059,
      #   "difficulty": "Hard",
      #   "length": "5.0 miles",
      #   "elevation": "2,000 ft",
      #   "route_type": "Out and Back",
      #   "description": "A challenging trail that leads to the summit of Lassen Peak, providing sweeping views of the park's volcanic landscape.",
      #   "attractions": "Volcanic Summit, Panoramic Views",
      #   "activities": "Hiking, Scenic Views",
      #   "suitability": "Experienced Hikers",
      # },
      # {
      #   "name": "Manzanita Lake Loop Trail",
      #   "park": "Lassen Volcanic National Park",
      #   "city": "Mineral",
      #   "state": "California",
      #   "lat": 40.5524,
      #   "long": -121.5590,
      #   "difficulty": "Easy",
      #   "length": "1.6 miles",
      #   "elevation": "50 ft",
      #   "route_type": "Loop",
      #   "description": "A leisurely loop trail that offers serene views of Manzanita Lake and the surrounding forest, perfect for a peaceful stroll.",
      #   "attractions": "Lake Views, Nature",
      #   "activities": "Hiking, Nature Walking",
      #   "suitability": "All Skill Levels, Family-friendly",
      # },
    ]


# @with_appcontext
def seed_trails(app):
    with app.app_context():
        for data in seed_data:
            trail = Trail(**data)
            db.session.add(trail)

        db.session.commit()


# @with_appcontext
def undo_trails(app):
    with app.app_context():
        if environment == "production":
            db.session.execute(
                f"TRUNCATE table {SCHEMA}.trails RESTART IDENTITY CASCADE;"
            )
        else:
            db.session.execute(text("DELETE FROM trails"))

        db.session.commit()



