"""empty message

Revision ID: 28e723720708
Revises: 
Create Date: 2023-05-22 16:50:12.277578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e723720708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('park', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.Column('elevation', sa.String(length=50), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('attractions', sa.String(length=255), nullable=False),
    sa.Column('activities', sa.String(length=255), nullable=False),
    sa.Column('suitability', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookmarks_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('cover', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_src', sa.String(length=255), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('bookmarks_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmarks_list_id'], ['bookmarks_lists.id'], ),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_src', sa.String(length=255), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_images')
    op.drop_table('bookmarks')
    op.drop_table('trail_images')
    op.drop_table('reviews')
    op.drop_table('bookmarks_lists')
    op.drop_table('users')
    op.drop_table('trails')
    # ### end Alembic commands ###
