"""empty message

Revision ID: 70bf46e80ffb
Revises: e61bfa5201f0
Create Date: 2023-06-18 19:03:06.817854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bf46e80ffb'
down_revision = 'e61bfa5201f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('followed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower', 'followed')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('default_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('default_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('follows')
    # ### end Alembic commands ###
